private_key_path = "privkey"
chain_id = "testing"
version = "v0_38"
# version = "v1_0"

[connection]
host = "192.168.0.5"
port = 26558
identity_key_path = "./privkey"
secret_connection_version = "v0_34"
