chain_id         = "testing"
version          = "v0_38"
signing_mode     = "vault_signer_plugin"
log_level        = "debug"

[raft]
node_id      = 1
bind_addr    = "127.0.0.1:7001"
data_path   = "./cluster-data/state_node1.json"
initial_state_path = ""

[[raft.peers]]
id = 1
addr = "127.0.0.1:7001"

[[connections]]
host              = "192.168.0.5"
port              = 36558

[[connections]]
host              = "192.168.0.5"
port              = 26558

[signing.vault]
address      = "http://127.0.0.1:8200"
token        = "root"
transit_path = "signer"
key_name     = "test-v4"
skip_verify  = true
