chain_id         = "beacond-2061"
# chain_id         = "story-1001511"
# chain_id         = "testing"
# version          = "v0_38"
version          = "v1_0"
signing_mode     = "vault_signer_plugin"
# signing_mode     = "native"
log_level        = "trace"

[raft]
node_id      = 1
bind_addr    = "127.0.0.1:7001"
data_path   = "./cluster-data/state_node1.json"
initial_state_path = ""

[[raft.peers]]
id = 1
addr = "127.0.0.1:7001"

[[connections]]
host              = "127.0.0.1"
port              = 26659

# [[connections]]
# host              = "192.168.0.5"
# port              = 36558

# [[connections]]
# host              = "192.168.0.5"
# port              = 26558

[signing.vault]
address      = "http://127.0.0.1:8200"
token        = "root"
transit_path = "signer"
key_name     = "test-v5-bera"
skip_verify  = true

[signing.native]
private_key_path     = "./keys/berachain"
key_type  = "bls12381"
