chain_id = "injective-888"
version = "v1_0"
node_id = 4000
peers = []
#peers = ["141.95.97.184:50002","51.91.74.235:50001"]
cluster_port = 50003
state_file = "consensus_state.json"
signing_mode = "native"

[[connections]]
host                   = "141.95.98.123"
port                   = 36658
identity_key_path = "./configs/privkey-2"

[signing.native]
private_key_path = "./configs/privkey-3"
key_type = "ed25519"
