private_key_path = "./configs/privkey-2"
chain_id         = "osmo-test-5"
version          = "v0_38"
node_id          = 4000
peers            = []
cluster_port     = 50003
state_file       = "./configs/consensus_state.json"
signing_mode = "vault"

[[connections]]
host              = "192.168.0.5"
port              = 26558
identity_key_path = "./configs/privkey-2"


[signing.vault]
address      = "http://127.0.0.1:8200"
token        = "root"
transit_path = "transit"
key_name     = "validator-key-simd"
cacert       = ""
skip_verify  = false
